jobs:
  code_format:
    name: Code Format
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: jcheckstyle
      run: ./sbt jcheckStyle
  test_jdk11:
    name: Test JDK11
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '11'
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-jdk11-${{ hashFiles('**/*.sbt') }}
        path: ~/.cache
        restore-keys: ${{ runner.os }}-jdk11-
    - continue-on-error: true
      name: Test
      run: ./sbt test
    - continue-on-error: true
      name: Universal Buffer Test
      run: ./sbt test -J-Dmsgpack.universal-buffer=true
  test_jdk17:
    name: Test JDK17
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-jdk17-${{ hashFiles('**/*.sbt') }}
        path: ~/.cache
        restore-keys: ${{ runner.os }}-jdk17-
    - continue-on-error: true
      name: Test
      run: ./sbt test
    - continue-on-error: true
      name: Universal Buffer Test
      run: ./sbt test -J-Dmsgpack.universal-buffer=true
  test_jdk21:
    name: Test JDK21
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-jdk21-${{ hashFiles('**/*.sbt') }}
        path: ~/.cache
        restore-keys: ${{ runner.os }}-jdk21-
    - continue-on-error: true
      name: Test
      run: ./sbt test
    - continue-on-error: true
      name: Universal Buffer Test
      run: ./sbt test -J-Dmsgpack.universal-buffer=true
  test_jdk8:
    name: Test JDK8
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '8'
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-jdk8-${{ hashFiles('**/*.sbt') }}
        path: ~/.cache
        restore-keys: ${{ runner.os }}-jdk8-
    - continue-on-error: true
      name: Test
      run: ./sbt test
    - continue-on-error: true
      name: Universal    Buffer Test
      run: ./sbt test -J-Dmsgpack.universal-buffer=true
name: CI
on:
  repository_dispatch:
    types: trigger-ga___CI.yml
