jobs:
  update_release_draft:
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: release-drafter/release-drafter@v6
name: Release Drafter
on:
  repository_dispatch:
    types: trigger-ga___release-drafter.yml
permissions:
  contents: read
