jobs:
  publish_snapshots:
    name: Publish snapshots
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 10000
    - continue-on-error: true
      run: git fetch --tags
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 11
    - continue-on-error: true
      env:
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASS }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USER }}
      name: Publish snapshots
      run: ./sbt publish
name: Snapshot Release
on:
  repository_dispatch:
    types: trigger-ga___snapshot.yml
